# Generated by Django 2.2.3 on 2019-07-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='order',
            new_name='id',
        ),
    ]
