# Generated by Django 2.2.3 on 2019-07-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20190710_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='emailid',
            new_name='email_id',
        ),
    ]
